# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dir_Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirSearchForm(object):
    def setupUi(self, DirSearchForm):
        DirSearchForm.setObjectName("DirSearchForm")
        DirSearchForm.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(DirSearchForm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 69, 355, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.textEdit_2 = QtWidgets.QTextEdit(DirSearchForm)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 100, 351, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(DirSearchForm)
        self.label.setGeometry(QtCore.QRect(30, 40, 291, 16))
        self.label.setObjectName("label")

        self.retranslateUi(DirSearchForm)
        QtCore.QMetaObject.connectSlotsByName(DirSearchForm)

    def retranslateUi(self, DirSearchForm):
        _translate = QtCore.QCoreApplication.translate
        DirSearchForm.setWindowTitle(_translate("DirSearchForm", "Form"))
        self.pushButton.setText(_translate("DirSearchForm", "选择目录字典"))
        self.pushButton_2.setText(_translate("DirSearchForm", "PushButton"))
        self.label.setText(_translate("DirSearchForm", "测试用例:https://www.imnu.edu.cn"))
