# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Is_lived.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IsLivedForm(object):
    def setupUi(self, IsLivedForm):
        IsLivedForm.setObjectName("IsLivedForm")
        IsLivedForm.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(IsLivedForm)
        self.pushButton.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(IsLivedForm)
        self.lineEdit.setGeometry(QtCore.QRect(20, 31, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(IsLivedForm)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label.setObjectName("label")

        self.retranslateUi(IsLivedForm)
        QtCore.QMetaObject.connectSlotsByName(IsLivedForm)

    def retranslateUi(self, IsLivedForm):
        _translate = QtCore.QCoreApplication.translate
        IsLivedForm.setWindowTitle(_translate("IsLivedForm", "Form"))
        self.pushButton.setText(_translate("IsLivedForm", "PushButton"))
        self.lineEdit.setText(_translate("IsLivedForm", "URL"))
        self.label.setText(_translate("IsLivedForm", "测试用例:192.168.31.30/30"))
