# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Port_Scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PortSacnForm(object):
    def setupUi(self, PortSacnForm):
        PortSacnForm.setObjectName("PortSacnForm")
        PortSacnForm.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(PortSacnForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 355, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(1120, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(PortSacnForm)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 16))
        self.label.setObjectName("label")

        self.retranslateUi(PortSacnForm)
        QtCore.QMetaObject.connectSlotsByName(PortSacnForm)

    def retranslateUi(self, PortSacnForm):
        _translate = QtCore.QCoreApplication.translate
        PortSacnForm.setWindowTitle(_translate("PortSacnForm", "Form"))
        self.lineEdit.setText(_translate("PortSacnForm", "URL"))
        self.comboBox.setItemText(0, _translate("PortSacnForm", "全端口扫描"))
        self.comboBox.setItemText(1, _translate("PortSacnForm", "部分端口扫描"))
        self.pushButton.setText(_translate("PortSacnForm", "PushButton"))
        self.label.setText(_translate("PortSacnForm", "测试用例:127.0.0.1        不建议用全端口扫描贼慢"))
