# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subdomain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubdomainForm(object):
    def setupUi(self, SubdomainForm):
        SubdomainForm.setObjectName("SubdomainForm")
        SubdomainForm.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(SubdomainForm)
        self.lineEdit.setGeometry(QtCore.QRect(16, 31, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(SubdomainForm)
        self.pushButton.setGeometry(QtCore.QRect(270, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(SubdomainForm)
        self.comboBox.setGeometry(QtCore.QRect(200, 30, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(SubdomainForm)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SubdomainForm)
        QtCore.QMetaObject.connectSlotsByName(SubdomainForm)

    def retranslateUi(self, SubdomainForm):
        _translate = QtCore.QCoreApplication.translate
        SubdomainForm.setWindowTitle(_translate("SubdomainForm", "Form"))
        self.lineEdit.setText(_translate("SubdomainForm", "URL"))
        self.pushButton.setText(_translate("SubdomainForm", "PushButton"))
        self.comboBox.setItemText(0, _translate("SubdomainForm", "1"))
        self.comboBox.setItemText(1, _translate("SubdomainForm", "2"))
        self.comboBox.setItemText(2, _translate("SubdomainForm", "3"))
        self.comboBox.setItemText(3, _translate("SubdomainForm", "4"))
        self.comboBox.setItemText(4, _translate("SubdomainForm", "5"))
        self.comboBox.setItemText(5, _translate("SubdomainForm", "6"))
        self.comboBox.setItemText(6, _translate("SubdomainForm", "7"))
        self.comboBox.setItemText(7, _translate("SubdomainForm", "8"))
        self.comboBox.setItemText(8, _translate("SubdomainForm", "9"))
        self.comboBox.setItemText(9, _translate("SubdomainForm", "10"))
        self.label.setText(_translate("SubdomainForm", "测试用例:baidu.com            10"))
