# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tcp_Is_lived.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TCPIsLived(object):
    def setupUi(self, TCPIsLived):
        TCPIsLived.setObjectName("TCPIsLived")
        TCPIsLived.resize(400, 337)
        self.pushButton = QtWidgets.QPushButton(TCPIsLived)
        self.pushButton.setGeometry(QtCore.QRect(200, 39, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(TCPIsLived)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(TCPIsLived)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 16))
        self.label.setObjectName("label")

        self.retranslateUi(TCPIsLived)
        QtCore.QMetaObject.connectSlotsByName(TCPIsLived)

    def retranslateUi(self, TCPIsLived):
        _translate = QtCore.QCoreApplication.translate
        TCPIsLived.setWindowTitle(_translate("TCPIsLived", "Form"))
        self.pushButton.setText(_translate("TCPIsLived", "PushButton"))
        self.lineEdit.setText(_translate("TCPIsLived", "URL"))
        self.label.setText(_translate("TCPIsLived", "测试用例:192.168.31.30/30"))
